In [2]:
import mysql.connector
import xlsxwriter

mydb = mysql.connector.connect(
    user = 'root',
    password = '123465',
    host = 'localhost',
    database = 'world'
)

In [3]:
# ############ MySQL to Excel ##################
# #############################################
## Read City's Table
cursor = mydb.cursor()
cursor.execute('SELECT * FROM city')
db1 = cursor.fetchall()
## Read Country's Table
cursor1 = mydb.cursor()
cursor1.execute('SELECT * FROM country')
db2 = cursor1.fetchall()
## Read Country Language's table
cursor2 = mydb.cursor()
cursor2.execute('SELECT * FROM countrylanguage')
db3 = cursor2.fetchall()


# #### Convert City table to list of list
head1 = ['ID','Name','CountryCode','District','Population']
dataExcel1 = []
dataExcel1.append(head1)
for i in db1:
    x = list(i)
    dataExcel1.append(x)
# print(dataExcel)

# #### Convert Country table to list oflist
head2 = ['Code','Name','Continent','Region','SurfaceArea',
'IndepYear','Population','LifeExpetancy','GNP','GNPOld','LocalName','GovernmentForm','HeadofState','Capital','Code2']
dataExcel2 = []
dataExcel2.append(head2)
for i in db2:
    x = list(i)
    dataExcel2.append(x)
# print(dataExcel1)

# #### COnvert CountryLanguage table to list of list
head3 = ['CountryCode','Language','IsOfficial','Percentage']
dataExcel3 = []
dataExcel3.append(head3)
for i in db3:
    x = list(i)
    dataExcel3.append(x)
# print(dataExcel2)

################ Write to Excel #####################

book = xlsxwriter.Workbook('World_Database.xlsx')
sheet1 = book.add_worksheet('City')
sheet2 = book.add_worksheet('Country')
sheet3 = book.add_worksheet('CountryLanguage')

row = 0
for i in dataExcel1:
    for j in range(len(i)):
        sheet1.write(row,j,i[j])
    row += 1
row = 0
for i in dataExcel2:
    for j in range(len(i)):
        sheet2.write(row,j,i[j])
    row += 1
row = 0
for i in dataExcel3
    for j in range(len(i)):
        sheet3.write(row,j,i[j])
    row += 1
book.close()

In [23]:
######### MySQL to CSV ###################
#########################################

Read City's Table
cursor = mydb.cursor(dictionary = True)
cursor.execute('SELECT * FROM city')
city = cursor.fetchall()
## Read Country's Table
cursor1 = mydb.cursor(dictionary = True)
cursor1.execute('SELECT * FROM country')
country = cursor1.fetchall()
## Read Country Language's table
cursor2 = mydb.cursor(dictionary = True)
cursor2.execute('SELECT * FROM countrylanguage')
countryLng = cursor2.fetchall()
print(city)
#### Write to csv ############################
#### Jalankan write satu persatu #############
import csv
# Write city
with open('City.csv','a',newline = '') as mycsv:
    write = csv.DictWriter(mycsv, delimiter=',',fieldnames = ['ID','Name','CountryCode','District','Population'])
    write.writerows(city)
## Write country
# with open('Country.csv','a',newline = '') as mycsv:
#     write1 = csv.DictWriter(mycsv, delimiter=',',fieldnames = ['Code','Name','Continent','Region','SurfaceArea','IndepYear','Population','LifeExpetancy','GNP','GNPOld','LocalName','GovernmentForm','HeadofState','Capital','Code2'])
#     write1.writerows(country)
## Write country language
# with open('CountryLanguage.csv','a',newline = '') as mycsv:
#     write2 = csv.DictWriter(mycsv, delimiter=',',fieldnames = ['CountryCode','Language','IsOfficial','Percentage'])
#     write2.writerows(countryLng)

In [24]:
######### MySQL to Json ###################
#########################################

## Read City's Table
cursor = mydb.cursor(dictionary = True)
cursor.execute('SELECT * FROM city')
city = cursor.fetchall()
## Read Country's Table
cursor1 = mydb.cursor(dictionary = True)
cursor1.execute('SELECT * FROM country')
country = cursor1.fetchall()
## Read Country Language's table
cursor2 = mydb.cursor(dictionary = True)
cursor2.execute('SELECT * FROM countrylanguage')
countryLng = cursor2.fetchall()

#### Write to json #####
import json

with open('City.json','w') as myJson:
    json.dump(city, myJson)
with open('Country.json','w') as myJson:
    json.dump(country, myJson)
with open('CountryLanguage.json','w') as myJson:
    json.dump(countryLng, myJson)